mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
# import all views here
from . import views
# define name of app
app_name= 'polls'
# define all url patterns here
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('user_home/', views.user_home, name='user_home'),
    path('error_user_home/', views.error_user_home, name='error_user_home'),
    path('addpoll/', views.addpoll, name='addpoll'),
    path('<int:question_id>/editpoll/', views.editpoll, name='editpoll'),
    path('<int:question_id>/editchoice/', views.editchoice, name='editchoice'),
    path('<int:question_id>/deletepoll/', views.deletepoll, name='deletepoll'),
    path('<int:question_id>/deletechoice/', views.deletechoice, name='deletechoice'),
    path('addchoice/', views.addchoice, name='addchoice'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('search/', views.search, name='search'),
]

polls/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

# Create your models here.
# model for storing user info
class User(AbstractUser):
    pass
# model for storing question info
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    MY_CHOICES = (('Anime', 'Anime'),('Football', 'Football'),('Framework', 'Framework'),('Other', 'Other'),)
    my_field = models.CharField(max_length=20, choices=MY_CHOICES, null=True)
    pub_date = models.DateTimeField('date published')
    username = models.CharField(max_length=20)

    def __str__(self):
        return self.question_text
# model for storing choice info
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
# model for storing editing choice info
class Change_choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    new_choice = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text
# model to ensure user only vote once
class Vote_count(models.Model):
    question_voted = models.IntegerField(default=0)
    voter = models.IntegerField(default=0)

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from .models import Question,Choice, Change_choice, Vote_count

# Create your forms here.
# postform for creating post
class PostForm(forms.ModelForm):
  

    class Meta:
        model = Question
        fields = ('question_text', 'my_field')
# choiceform for craeting choices
class ChoiceForm(forms.ModelForm):
  

    class Meta:
        model = Choice
        fields = ('question', 'choice_text')
# choice_edit_form for editing choices
class Choice_edit_Form(forms.ModelForm):
  
    class Meta:
        model = Change_choice
        fields = ('question', 'choice_text','new_choice')
# form for ensuring user only vote once
class Voted_count(forms.ModelForm):
    class Meta:
        model = Vote_count
        fields = ('question_voted','voter')

polls/views.py
# import all packages and modules here
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from json import dumps
from .models import User,Question,Choice, Vote_count
from .forms import PostForm, ChoiceForm, Choice_edit_Form, Voted_count
from django.utils import timezone
#global que
#Pollapp homepage function
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {'latest_question_list': latest_question_list,}
    return render(request, 'polls/index.html', context)
#User login function
def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful')
            return HttpResponseRedirect(reverse('polls:user_home'))
        else:
            return render(request, "polls/login.html", {
            "errmessage": "Invalid username and/or password."
            })
    else:
        return render(request, "polls/login.html")

#User logout function
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("polls:index"))

#User Register function
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        # Attempt to create new user and ensure all fields are filled
        if username and email and password and confirmation is not None:
            # Ensure password matches confirmation
            if password != confirmation:
                return render(request, "polls/register.html", {
                    "errmessage": "Passwords must match."
                })
            try:
                user = User.objects.create_user(username, email, password)
                user.save()
            except IntegrityError:
                return render(request, "polls/register.html", {
                    "errmessage": "Username already taken."
                })
            login(request, user)
            messages.success(request, 'Login Successful')
            return HttpResponseRedirect(reverse('polls:user_home')) 
        # if error then display error
        else:
            return render(request, "polls/register.html", {
                "errmessage": "Fill all fields"
            })
    else:
        return render(request, "polls/register.html")
#View after user login
def user_home(request):
    question_list = Question.objects.all().order_by('-pub_date')
    return render(request,'polls/userhome.html',{'question_list':question_list})

#view for userhome in case already voted
def error_user_home(request):
    question_list = Question.objects.all().order_by('-pub_date')
    error_message="Sorry, but you have already voted."
    return render(request,'polls/userhome.html',{'question_list':question_list,'error_message':error_message})
#View for adding new poll
def addpoll(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.username = request.user
            post.save()
            return redirect("polls:addpoll")
    else:
        form = PostForm()
        return render(request=request, template_name="polls/addpoll.html", context={'form': form})
# view for adding choices
def addchoice(request):
    if request.method == "POST":
        form = ChoiceForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect("polls:addchoice")
    else:
        form = ChoiceForm()
        return render(request=request, template_name="polls/addchoice.html", context={'form': form})

#To edit poll question and category
def editpoll(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.pub_date = timezone.now()
            question.save()
            return redirect('polls:user_home')
    else:
        form = PostForm()
        return render(request,'polls/editpoll.html',{'form':form,'question':question,})

#To edit choice list
def editchoice(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = Choice_edit_Form(request.POST, instance=question)
        if form.is_valid():
            old_choice = form.cleaned_data['choice_text']
            new_choice = form.cleaned_data['new_choice']
            Choice.objects.filter(choice_text=old_choice).update(choice_text=new_choice)
            return redirect('polls:user_home')
    else:
        form = Choice_edit_Form()
        return render(request,'polls/editchoice.html',{'form':form,'question':question,})
# delete a poll
def deletepoll(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('polls:user_home')
# delete a choice from poll
def deletechoice(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = ChoiceForm(request.POST, instance=question)
        if form.is_valid():
            old_choice = form.cleaned_data['choice_text']
            Choice.objects.filter(choice_text=old_choice).delete()
            return redirect('polls:user_home')
    else:
        form = ChoiceForm()
        return render(request,'polls/deletechoice.html',{'form':form,'question':question,})
#View for displaying full poll view
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    #to ensure only owner of the poll can edit the poll
    if str(request.user) == question.username:
        var=1
    else:
        var=0
    return render(request, 'polls/detail.html', {'question': question,'var':var})
#Display vote count in the form of charts
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    #To display result chart get all choices and their count
    l=question.choice_set.all()
    xval=[item.choice_text for item in l]
    yval = [item.votes for item in l]
    #save the ids of user voted to ensure vote only once
    form = Voted_count()
    my_obj = form.save(commit=False)
    my_obj.question_voted = question_id
    my_obj.voter = request.user.id
    my_obj.save()
    return render(request, 'polls/results.html', {'question': question, 'xval':dumps(xval), 'yval':dumps(yval)})
#View for counting the votes for each choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    #check whether user already voted
    if Vote_count.objects.filter(question_voted=question_id, voter=request.user.id).exists():
        messages.error(request, 'already voted')
        return redirect('polls:error_user_home')
    #if not voted increase the vote count
    else:
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


#search method
def search(request):        
    if request.method == 'GET': # this will be GET now      
        que_name =  request.GET.get('poll_instance') # get the input value 
        print(que_name)    
        try:
            status = Question.objects.filter(question_text__icontains=que_name) # filter returns a  matching list 
            print(status)
        except Exception as e:     #exception handling
            messages.error(request, e)
            return redirect('polls:error_user_home')
        else:
            return render(request,"polls/search.html",{"poll":status})
    else:
        return render(request,"polls/search.html",{})

polls/templates/polls/account_layout.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
  <head>
    <!-- define character set and responsive viewport -->
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- display title in web page tab  -->
    <title>Poll House</title> 
    <!-- icon for title -->
    <link rel = "icon" href ="{% static "polls/image/title_icon.png" %}" type = "image/x-icon">
    <!-- js scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <!-- link to external css style sheets  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>  

  <body>
    <!-- navigation bar for user account page -->
      <nav class="navbar navbar-expand-lg navbar-dark text-light bg-danger">
        <a class="navbar-brand" href="#"><i class="fa fa-fw fa-home"></i> POLL HOUSE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <!-- only show more options if user logged in else login-->
            {% if user.is_authenticated %}
                <a class="nav-item nav-link active" href="{% url 'polls:user_home' %}">All Polls<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'polls:addpoll' %}">Add Poll&Choice</a>
                <a class="nav-item nav-link active" href="{% url 'polls:logout' %}">Logout</a>
                <form action="{% url 'polls:search' %}" name="myform" method="GET" class="form-inline my-2 my-lg-0" style="padding-left: 850px;">
                  <input class="form-control mr-sm-2" type="search" name="poll_instance" id="poll_instance" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
                </form>
                <a class="nav-item nav-link active"  style="padding-left:50px;" href="#">Welcome {{request.user.username.title}}</a> 
            {% else %}
              <a class="nav-item nav-link active" href="{% url 'polls:index' %}">HOME<span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link" href="{% url 'polls:login' %}">LOGIN</a>
              <a class="nav-item nav-link" href="{% url 'polls:register' %}">REGISTER</a>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>
      <div class="cardblock">  <!-- this block is extended -->
          {% block body %}
          {% endblock %}
      </div>
  </body>  
</html> 

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
    <head>  
        <!-- define character set and responsive viewport-->
        <meta charset="UTF-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- define title of the page and icon -->
        <title>Poll House</title>  
        <link rel = "icon" href ="{% static "polls/image/title_icon.png" %}" type = "image/x-icon"> 
        <!-- link the external css style sheets -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    </head>
    
    <body>
        <!-- navigation bar -->
        <nav class="navbar navbar-dark text-light bg-success" style="height: 60px;">
            <div style="text-align: center;">
                <a class="navbar-brand" href="{% url 'polls:user_home' %}"><i class="fa fa-fw fa-home"></i> POLL HOUSE</a>
            </div>
            <a class="card-link text-light"  href="{% url 'polls:user_home' %}">HOME</a>
        </nav>
        <br>
        <!-- poll question images are displayed here -->
        <div class="card" style="width: 800px; margin:0 auto;">
            {% if 'Anime' in question.my_field %}
                <img class="card-img-top" src= "{% static 'polls/image/img.jpg' %}" alt="Card image cap">     <!--Anime image-->
            {% endif %}

            {% if 'Football' in question.my_field %}
                <img class="card-img-top" src= "{% static 'polls/image/img1.jpg' %}" alt="Card image cap">    <!--Football image-->
            {% endif %}

            {% if 'Framework' in question.my_field %}
                <img class="card-img-top" src= "{% static 'polls/image/img3.jpg' %}" alt="Card image cap">    <!--Framework image-->
            {% endif %}

            {% if 'Other' in question.my_field %}
                <img class="card-img-top" src= "{% static 'polls/image/img4.jpg' %}" alt="Card image cap">    <!--Other image-->
            {% endif %}
        <!-- poll question and choices are displayed in the form here -->
        <div class="card-body">
            <h5 class="card-title">{{ question.question_text }}</h5>
            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
                <fieldset>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    <ul class="list-group list-group-flush">
                        {% for choice in question.choice_set.all %}
                            <li class="list-group-item"><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br></li>
                        {% endfor %}
                    </ul>
                </fieldset>
            
                <div class="card-body">
                    <input type="submit" value="Vote"><br><br>  <!--button to submit vote-->
                    <a class="btn btn-dark" href="{% url 'polls:results' question.id %}"><span class="glyphicon glyphicon-pencil">Results</span></a>
                    <!-- only display options if user is owner of poll -->
                    {% if var %}
                        <a class="btn btn-dark" href="{% url 'polls:editpoll' question.id %}"><span class="glyphicon glyphicon-pencil">Edit poll</span></a>
                        <a class="btn btn-dark" href="{% url 'polls:editchoice' question.id %}"><span class="glyphicon glyphicon-pencil">Edit Choice</span></a>
                        <a class="btn btn-dark" href="{% url 'polls:deletepoll' question.id %}"><span class="glyphicon glyphicon-pencil">Delete poll</span></a>
                        <a class="btn btn-dark" href="{% url 'polls:deletechoice' question.id %}"><span class="glyphicon glyphicon-pencil">Delete choice</span></a>
                    {% endif %}
                    
                </div>
            </form>
        </div>
        </div>
        <!--JS/JQUERY LIBRARIES-->
        <!--<script src="{% static 'polls/js/bootstrap.min.js' %}"></script>-->
    </body>  
</html> 

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
    <head>  
        <!-- define character set and responsive viewport-->
        <meta charset="UTF-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- define title of web page -->
        <title>Poll House</title>  
        <!--  external js scripts -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <!-- external css are linked -->
        <link rel = "icon" href ="{% static "polls/image/title_icon.png" %}" type = "image/x-icon">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
        

    </head>  

    <body id="indexbg">
        <!-- navigation bar -->
        <nav class="navbar navbar-expand-lg navbar-dark text-light bg-primary">
            <a class="navbar-brand" href="#"><i class="fa fa-fw fa-home"></i> POLL HOUSE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'polls:index' %}">HOME<span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link active" href="{% url 'polls:login' %}">LOGIN</a>
                    <a class="nav-item nav-link active" href="{% url 'polls:register' %}">REGISTER</a>
            </div>
            </div>
        </nav>
        <br>
        
        <!-- all polls are displayed here -->
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <a href="#" onclick="myfunction()">  <!-- when user clicks alert button displays to login -->
                    <div class="card text-white bg-info mb-3" style="width: 20rem; text-align:center;display:inline-block;">
                        <div class="card-header">Poll: {{ question.question_text }}</div>
                            <div class="card-body">
                                <h5 class="card-title">CLICK!!!</h5>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
            </ul>
        <!-- if no polls are available this block executes -->
        {% else %}
            <div id="pollblock">
                <div class="row">
                    <div class="card text-white bg-danger col-sm-3 mb-3 align-items-center">
                        <div class="card-header">No Poll Here</div>
                            <div class="card-body">
                                <h5 class="card-title">Create Poll To Post!!!</h5>
                            </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <!-- InternalJS/JQUERY LIBRARIES included-->
        <script src="{% static 'polls/js/script.js' %}"></script>
    </body>  
</html> 

polls/templates/polls/layout.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  
  <head>
      <!-- define character set and responsive viewport -->
      <meta charset="UTF-8">  
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- define title of webpage -->
      <title>Poll House</title> 
       <!-- external js scripts included  -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <!--  external css stylesheets included -->
      <link rel = "icon" href ="{% static "polls/image/title_icon.png" %}" type = "image/x-icon">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
  </head>  
  <body id="layoutbg">
    <!-- navigation bar -->
      <nav class="navbar navbar-expand-lg navbar-dark text-light bg-primary">
        <a class="navbar-brand" href="#"><i class="fa fa-fw fa-home"></i> POLL HOUSE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <!-- if user is login only display options -->
            {% if user.is_authenticated %}
                <a class="nav-item nav-link active" href="{% url 'polls:user_home' %}">All Polls<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'polls:addpoll' %}">Add Poll&Choice</a>
                <a class="nav-item nav-link active" href="{% url 'polls:logout' %}">Logout</a>
                <a class="nav-item nav-link active"  style="padding-left:1270px;" href="#">Welcome {{request.user.username.title}}</a> 
            <!-- if not login then login to continue -->
            {% else %}
              <a class="nav-item nav-link active" href="{% url 'polls:index' %}">HOME<span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link" href="{% url 'polls:login' %}">LOGIN</a>
              <a class="nav-item nav-link" href="{% url 'polls:register' %}">REGISTER</a>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>
      <div class="cardblock">  <!-- this block is extended -->
          {% block body %}
          {% endblock %}
      </div>


  </body>  
</html> 

polls/templates/polls/login.html
{% extends "polls/layout.html" %}
{% load static %}
{% block body %}
    <!-- display error message if login is incorrect -->
    {% if errmessage %}
        <div class="errmsg">{{ errmessage }}</div>
    {% endif %}
    <!-- div block for login form -->
    <div class="formblock" id="formblock">
        <form action="{% url 'polls:login' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Login</legend>
                <div class="form-group">
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <input class="btn btn-primary" type="submit" value="Login">
            </fieldset>
        </form>
    
        Don't have an account? <a href="{% url 'polls:register' %}" style="color: white;">Register here.</a>
    </div>
{% endblock %}